[package]
name = "physics-rocks"
version.workspace = true
edition.workspace = true

[dependencies]
physics-core = { path = "../core" }
rocksdb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
